admin/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from apps.base import urls as base_urls
from apps.aperitivo import urls as aperitivo_urls
from apps.modulos import urls as modulos_urls
from apps.turmas import urls as turmas_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('contas/', include('django.contrib.auth.urls')),
    path('', include(base_urls), name='home'),
    path('aperitivo/', include(aperitivo_urls)),
    path('modulos/', include(modulos_urls)),
    path('turmas/', include(turmas_urls)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

apps/aperitivo/urls.py
from django.urls import path
from apps.aperitivo.views import video, indice


app_name = 'aperitivo'
urlpatterns = [
    path('<slug:slug>', video, name='video'),
    path('', indice, name='indice')
]

apps/base/urls.py
from django.urls import path
from apps.base.views import home

app_name = 'base'
urlpatterns = [
    path('', home, name='home')
]

apps/base/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given email, and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    App base User Class

    Email and password are required. Other fields are optional.
    """

    first_name = models.CharField(_('first name'), max_length=150, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s' % self.first_name
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

apps/base/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'base/index.html')

apps/base/templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Dacio Lima{% endblock %}</title>

    <meta name="description" content="{% block description %}Projeto no Curso PythonPro{% endblock %}">
    <meta name="author" content="Dácio Lima">
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>
<body>

<div class="container">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!--		<a class="navbar-brand" href="{% url 'base:home' %}">DL-DEV</a>-->
        <!--		<a class="navbar-brand" href="{% url 'aperitivo:indice' %}">Aperitivo</a>-->

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Módulos
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% for modulo in MODULOS %}
                        <a class="dropdown-item" href="{{ modulo.get_absolute_url }}">{{ modulo.titulo }}</a>
                        <div class="dropdown-divider"></div>
                        {% endfor %}

                    </div>
                </li>

            </ul>

            {% if user.is_authenticated %}

            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link">{{ user.first_name }}</a>
                </li>

                <li class="nav-item active">
                    <a class="btn btn-light" href="{% url 'logout' %}">Sair</a>
                </li>
            </ul>

            {% else %}
            <a class="btn btn-light" href="{% url 'login' %}">Entrar</a>
            {% endif %}

        </div>


    </nav>

    {% block content %} {% endblock %}

</div>

{% include "base/footer.html" with contato_email='dacio@email.com' only %}

<script src="/static/js/jquery.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
</body>
</html>

apps/base/templates/base/footer.html
<footer class="main-footer mt-4 pt-5 text-light">
	<div class="container">
		<div class="row">
			<div class="col">
				<h4>Contato</h4>
				<address>
					+55 xx xxxxx-xxxx
					<br/>
					<a href="mailto:{{contato_email}}" class="text-light">{{contato_email}}</a>
				</address>
			</div>
		</div>
	</div>
	<div class="rights pb-2 pt-2">
		<div class="container">
			<div class="row">
				<div class="col">
					{% now 'Y' %} Todos os direitos reservados.
				</div>
			</div>
		</div>
	</div>
</footer>

apps/base/templates/base/index.html
{% extends "base/base.html" %}

{% load static %}

<title>{% block title %}Dacio Lima - Home{% endblock title %}</title>
{% block description %}Conteúdo gratuítos de Python{% endblock %}


{% block content %}
	<div class="row">
		<div class="col-md-12">

			<div class="jumbotron">
				<h2>
					<strong>Dácio Lima</strong>
				</h2>

				<h4 class="mt-4">Teste de gateway de pagamento</h4>
				<!-- INICIO DO BOTAO PAGSEGURO -->
								<a href="https://pag.ae/7Ws7cSZw7/button" target="_blank" title="Pagar com PagSeguro"><img src="//assets.pagseguro.com.br/ps-integration-assets/botoes/pagamentos/205x30-pagar.gif" alt="Pague com PagSeguro - é rápido, grátis e seguro!" /></a>
				<!-- FIM DO BOTAO PAGSEGURO --><!-- FIM DO BOTAO PAGSEGURO -->



				<!--				<h4 class="mt-4">Lista de Espera de Curso</h4>-->
				<!--				<form action="https://gmail.us2.list-manage.com/subscribe/post?u=90827c4dddd70fd964d34a598&amp;id=19b20dec8b" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="form-row align-items-center" target="_blank" novalidate>-->
				<!--					<div class="form-row align-items-center">-->
				<!--						<div class="col-auto">-->
				<!--							<label class="sr-only" for="mce-EMAIL">Email</label>-->
				<!--							<input type="email" value="" name="EMAIL" class="form-control required" id="mce-EMAIL" placeholder="Digite seu email">-->
				<!--						</div>-->

				<!--						<div class="col-auto">-->
				<!--							<label class="sr-only" for="mce-FNAME">Nome</label>-->
				<!--							<input type="email" value="" name="FNAME" class="form-control" id="mce-FNAME" placeholder="Digite seu nome">-->
				<!--						</div>-->

				<!--						<div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_90827c4dddd70fd964d34a598_19b20dec8b" tabindex="-1" value=""></div>-->

				<!--						<div class="col-auto">-->
				<!--							<input type="submit" value="Cadastrar" name="subscribe" id="mc-embedded-subscribe" class="btn btn-primary">-->
				<!--						</div>-->
				<!--					</div>-->
				<!--				</form>-->

			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<div class="card">
				<h5 class="card-header">
					About
				</h5>
				<div class="card-body">
					<p class="card-text">
						<img  class="img-thumbnail float-left mr-3 foto_perfil" src="{% static 'img/perfil.png' %}" alt="Foto Dácio Lima">
					</p>

					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tristique sapien sed auctor faucibus. Suspendisse quis libero sit amet elit fringilla elementum. Aenean pharetra vehicula dictum. Praesent mattis eros congue leo commodo, blandit ullamcorper eros viverra. Mauris ultrices dolor in lacus dignissim tempor. Quisque pharetra consectetur nulla, vitae luctus lorem blandit vitae. Nulla vitae aliquam purus. Cras volutpat justo aliquet ex volutpat pretium. Quisque lectus purus, tincidunt non nisl eget, vulputate tincidunt mauris. Maecenas semper lorem velit, eu pretium lectus congue eget. Duis placerat mauris est, eget feugiat libero aliquam at.
Maecenas varius sapien ante, quis lacinia lorem tincidunt commodo. Integer urna lectus, accumsan vitae mauris ut, imperdiet porta tellus. Curabitur id diam viverra, fermentum dolor eu, consequat diam. Nunc vestibulum leo in tortor bibendum luctus. Vivamus dui nunc, porta at mauris sed, tempor viverra nunc. Proin feugiat sed metus sit amet rutrum. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Proin volutpat purus eu faucibus semper. Nam eleifend eleifend eros, vehicula lacinia odio hendrerit et. Mauris vitae dictum diam, a vulputate justo. Aenean quis nisi dapibus, dictum lorem ac, luctus ligula. Nulla eu porttitor tortor. Vestibulum imperdiet accumsan maximus. Cras ex sapien, placerat gravida lacinia eget, varius et mauris. Nunc maximus risus in enim vulputate rhoncus. Maecenas dictum urna id consequat consequat. Ut lobortis metus vel ante convallis facilisis. Curabitur ornare enim id ex condimentum blandit. Integer turpis neque, sagittis ac hendrerit in, commodo sit amet velit.

				</div>
			</div>
		</div>
	</div>
{% endblock %}